setwd("D:\\Personal\\ExploratoryDataAnalysis\\Project1\\ExData_Plotting1")
energy <- read.table("household_power_consumption.txt", sep =";", header = TRUE, na.strings = c("?",""))
energy$DateNew <- with(energy, as.Date(as.character(Date), "%d/%m/%Y"))
energyFeb <- subset(energy,DateNew=="2007-02-01" |  DateNew=="2007-02-02")
energyFeb$DateTime <- with(energyFeb,strptime(paste(DateNew,Time), "%Y-%m-%d %H:%M:%S"))
png(filename = "Plot2.png",width = 480, height = 480, units = "px", type = "windows")
with(energyFeb, plot(DateTime,Global_active_power,type ="l", xlab = "",main = "",ylab = "Global Active Power (kilowatts)"))
dev.off()